kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: static-vs-dynamic-secrets-demo
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30432
        hostPort: 5432
        protocol: TCP
      - containerPort: 30082
        hostPort: 8200
        protocol: TCP
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
      - containerPort: 30443
        hostPort: 8443
        protocol: TCP
      - containerPort: 32222
        hostPort: 2222
        protocol: TCP
